UserInterface/Controllers/ChannelController.cs
using System.Web.Mvc;
using Commands;

namespace UserInterface.Controllers
{
    public class ChannelController : Controller
    {
        //
        // GET: /Channel/

        public ActionResult Index()
        {
            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            var query = service.GetChannels();

            return View(query);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(CreateNewChannelCommand command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();

            service.CreateNewChannel(command);

            return RedirectToAction("");
        }
    }
}

UserInterface/Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Commands;

namespace UserInterface.Controllers
{
    public class TweetController : Controller
    {
        //
        // GET: /Tweet/

        public ActionResult Index(string channelname="")
        {
            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            var query = service.GetTweets();

            var channels = service.GetChannels().Select(channel => new SelectListItem()
                                                                       {
                                                                           Text = channel.Name, 
                                                                           Value = channel.Id.ToString()
                                                                       }).ToList();

            ViewBag.Channels = channels;

            ViewBag.GetChannelName = new Func<string, string>(n =>
            {
                var channel = channels.SingleOrDefault(m => m.Value == n);
                if (channel == null || channel.Value == Guid.Empty.ToString())
                {
                    return "Default";
                }

                return channel.Text;
            });

            ViewBag.GetChannelIdByName = new Func<string, Guid>(n =>
            {
                var channel = channels.SingleOrDefault(m => m.Text == n);
                if (channel == null || channel.Value == Guid.Empty.ToString())
                {
                    return Guid.Empty;
                }

                return Guid.Parse(channel.Value);
            });

             if (!string.IsNullOrEmpty(channelname))
            {
                query = query.Where(n => n.Channel == ViewBag.GetChannelIdByName(channelname)).ToArray(); 
            }

            return View(query);
        }

        public ActionResult Add()
        {
            ViewBag.Channels = new List<SelectListItem>();

            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            foreach (var channel in service.GetChannels())
            {
                ViewBag.Channels.Add(new SelectListItem()
                {
                    Text = channel.Name,
                    Value = channel.Id.ToString()
                });
            }

            return View();
        }

        [HttpPost]
        public ActionResult Add(PostNewTweetCommand command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            service.Execute(command);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(DeleteTweetCommand command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            service.Delete(command);

            return RedirectToAction("Index");
        }
    }
}

UserInterface/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace UserInterface.Controllers
{
    [Authorize(Roles="Admin")]
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult Index(string id)
        {
            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            var query = service.GetUsers();

            if (id != null)
            {
                query = query.Where(n => n.Id.ToString() == id).ToArray();
            }

            return View(query);
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Details(string id)
        {
            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            var query = service.GetUsers();

            if (id == null)
            {
                RedirectToAction("Index");
            }

            query = query.Where(n => n.Id.ToString() == id).ToArray();

            return View(query.Single());
        }

        [HttpPost]
        public ActionResult Add(Models.UserModel item)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            service.CreateUser(new Commands.CreateUserCommand()
                {
                    Username = item.Username
                });

            return RedirectToAction("Index");
        }

        public ActionResult Edit(string userId="")
        {
            var idGuid = Guid.Empty;

            if (!Guid.TryParse(userId, out idGuid))
            {
                RedirectToAction("Index");
            }

            var service = new ReadModelService.SimpleTwitterReadModelServiceClient();
            var query = service.GetUsers().SingleOrDefault(n => n.Id == idGuid);

            return View(Models.UserModel.FromReadModel(query));
        }

        [HttpPost]
        public ActionResult Edit(Models.UserModel item)
        {
            var properties = new List<string>()
            {
                "Username",
                "FirstName",
                "LastName",
                "Email",
                "IsAdmin"
            };

            foreach (var property in properties)
            {
                var propInfo = item.GetType().GetProperty(property);
                if (propInfo == null)
                {
                    continue;
                }
                
                var val = propInfo.GetValue(item, null);
                if (val == null)
                {
                    continue;
                }

                SetProperty(new Commands.SetUserPropertyCommand
                {
                    UserID = item.Id,
                    Name = property,
                    Value = val.ToString()
                });
            }

            return RedirectToAction("Details", new { id=item.Id });
        }

        static void SetProperty(Commands.SetUserPropertyCommand command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            if (command.Name == "IsAdmin")
            {
                if (command.Value == true.ToString())
                {
                    service.AddUserToRole(new Commands.AddUserToRoleCommand()
                        {
                            UserID = command.UserID,
                            Role = "Admin"
                        });
                }
                else
                {
                    service.RemoveUserFromRole(new Commands.RemoveUserFromRoleCommand()
                        {
                            UserID = command.UserID,
                            Role = "Admin"
                        });
                }
            }
            
            service.SetUserProperty(command);
        }

        public ActionResult Delete(Commands.DeleteUserCommand command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            service.DeleteUser(command);

            return RedirectToAction("Index");
        }

        public ActionResult SetPassword(Guid id)
        {
            var model = new Models.ChangePasswordModel();
            // todo: Verify that user has setpassword permission
            model.UserID = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult SetPassword(Models.ChangePasswordModel command)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            service.SetUserPassword(new Commands.SetUserPasswordCommand()
                {
                    UserID = command.UserID,
                    Password = command.NewPassword
                });

            return RedirectToAction("Details", new { id = command.UserID });
        }

        [HttpPost]
        public ActionResult Validate(string username, string submittedPassword)
        {
            var service = new Commanding.SimpleTwitterCommandServiceClient();
            var readModel = new ReadModelService.SimpleTwitterReadModelServiceClient();
            
            var user = readModel.GetUsers().Where(n => n.Username == username).SingleOrDefault();

            if (user == null)
            {
                return View(false);
            }

            service.ValidateUser(new Commands.ValidateUserCommand()
            {
                UserID = user.Id,
                Username = username,
                Password = submittedPassword 
            });

            bool result = readModel.UserValidated(user.Id);

            return View(result);
        }

        
    }

}

UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/AjaxLogin.js")" type="text/javascript"></script>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("CQRS Site Engine", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Tweets", "Index", "Tweet")</li>
                            <li>@Html.ActionLink("Channels", "Index", "Channel")</li>
                            <li>@Html.ActionLink("Users", "Index", "User")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

UserInterface/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", null, new { @class = "username" })!
        @Html.ActionLink("Log Off", "LogOff", "Account")
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Log on", "LogOn", "Account", routeValues: null, htmlAttributes: new { id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}